Added an optional local port definition
elliotchance/sshtunnel pull request #4
Opened 2020-01-14 15:10 UTC by rnsc

This commit simply adds the support for a local port definition when creating a tunnel.
The default will be to keep a random port unless specified.

2020-01-14 22:37 UTC, elliotchance requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/elliotchance/sshtunnel/4)* status: all files reviewed, 1 unresolved discussion (waiting on @rnsc)

___
*[ssh_tunnel.go, line 86 at r1](https://reviewable.io/reviews/elliotchance/sshtunnel/4#-LyaAVf47x7c0fFmCQjs:-LyaAVf47x7c0fFmCQjt:b-mhu317) ([raw file](https://github.com/elliotchance/sshtunnel/blob/fe995f6314e95e0543db7419585de74a0c1f3685/ssh_tunnel.go#L86)):*
> ```Go
> }
> 
> func NewSSHTunnel(tunnel string, auth ssh.AuthMethod, destination string, localport ...string) *SSHTunnel {
> ```

I agree this change is needed. However, I don't like optional parameters in this way. Being more explicit catches mistakes and is more robust to future changes. How about?

```go
// NewSSHTunnel creates a new single-use tunnel. Supplying "0" for localport will use a random port.
func NewSSHTunnel(tunnel string, auth ssh.AuthMethod, destination, localport string) *SSHTunnel
```


<!-- Sent from Reviewable.io -->

2020-01-15 06:21 UTC, rnsc commented
@elliotchance I did the change you asked, I agree it's better this way.
My intention was to keep backward compatibility for people using your library.

2020-01-15 06:24 UTC, elliotchance approved these changes
Yes, sometimes it's a delicate balance between providing new features and not interrupting the existing ones. You will need to make one more change, to the README example with the new parameter and description. Thanks!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/elliotchance/sshtunnel/4#-:-Lybrg3v-rRFqOLGfwCu:b-81nk9o)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-01-15 06:28 UTC, rnsc commented
@elliotchance cool, I updated the README, let me know if the wording is ok (english is not my native language)

2020-01-15 23:06 UTC, elliotchance approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/elliotchance/sshtunnel/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-01-15 23:07 UTC, merged